# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        language: system
        entry: poetry run flake8
        require_serial: true
        types: [python]
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: poetry run black --preview
        require_serial: true
        types_or: [python, pyi]
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: poetry run isort --filter-files
        require_serial: true
        types_or: [python, pyi, cython]
