_commit: 1.3.0
_src_path: git@gitlab.flowtale.ai:flowtale/internal/cookiecutter-python.git
author_email: mtn@flowtale.ai
author_name: Flowtale
distribution_name: copier-python-template
generate_docs: none
generate_example_code: false
git_hosting: gitlab
ide: vscode
license: MIT license
max_line_length: 88
type_checker: "mypy"
type_checker_strictness: "gradual"
package_name: template
package_type: library
project_name: Copier python template
project_short_description: Opinionated copier template for python projects
python_version: '3.10'
testing_framework: pytest
use_lint_strict_rules: false
use_jupyter_notebooks: false
version: 1.3.0
