image: "python:3.10"

stages:
  - .pre
  - test_and_lint

before_script:
  - apt-get update && apt-get install -y make
  - pip install poetry==1.8.3
  - make setup-strict

test:
  stage: test_and_lint
  script:
    - poetry run tox

linting:
  stage: test_and_lint
  script:
    - poetry run pre-commit run --all-files
