  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: "template"
      - id: end-of-file-fixer
        exclude: "template"

  - repo: local
    hooks:
      - id: black
        name: Format files with black
        exclude: "template"
        language: system
        entry: poetry run black --preview
        require_serial: true
        types_or: [python, pyi]
      - id: ruff-lint
        name: Lint files with ruff
        exclude: "template"
        entry: poetry run ruff check
        language: system
        require_serial: true
        types_or: [python, pyi, jupyter]
        args:
          - --fix
          - --show-fixes
          - --force-exclude
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        name: mypy
        exclude: "template"
        entry: poetry run mypy
        args: ["."]
        language: system
        pass_filenames: false
