  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format
        language: system
        require_serial: true
        types_or: [python, pyi]
        args:
        - --diff

      - id: ruff-lint
        name: ruff-lint
        entry: poetry run ruff check
        language: system
        require_serial: true
        types_or: [python, pyi]
        args:
          - --fix
          - --show-fixes
