#!/usr/bin/env bash
die() { test -n "$@" && echo "$@"; exit 1; } >&2

usage ()
{
echo "Usage: ./provision-deploy COMMAND TARGET [ANSIBLE_OPTION ...]

Positional arguments:
COMMAND          Command to be executed {provision, deploy}
TARGET           Target hostname or group of machines {${POSSIBLE_TARGETS[*]}}

Optional arguments:
  ANSIBLE_OPTION  Optional argument directly passed to ansible-playbook
"
exit 1
}

ANSIBLE_DIR="$(dirname "$0")/../ansible"
POSSIBLE_COMMANDS=(provision deploy)
POSSIBLE_TARGETS=(production lab vagrant)

command="$1"
target="$2";
shift 2

if [[ ! "${POSSIBLE_COMMANDS[*]}" =~ ${command} ]]; then
    usage
fi

if [[ ! "${POSSIBLE_TARGETS[*]}" =~ ${target} ]]; then
    # If it is a hostname it must be present in the inventory file
    if ! grep -q "${target}" "${ANSIBLE_DIR}/inventory.yml"; then
        usage
    fi
fi

ansible-playbook "$@" \
    -i "${ANSIBLE_DIR}/inventory.yml" \
    -l "${target}" \
    "${ANSIBLE_DIR}/${command}.yml"
