Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.network "private_network", ip: "192.168.100.4"

  config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y python3 python3-pip
      ln -s /usr/bin/python3 /usr/bin/python
  SHELL

  config.vm.provider "virtualbox" do |v|
      v.memory = 4096
  end
end
